services:
  db:
    image: postgres:16-alpine
    container_name: pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vjnjh421
      POSTGRES_DB: prompt_db
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/datax
      - ./db/init.sql:/docker-entrypoint-initdb.d/001-init.sql:ro

  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8001:8000"
    depends_on:
      - db

  redis:
    image: redis:6-alpine
    ports:
      - "6381:6379"
    depends_on:
     - app

  worker:
    build: .
    command: python3 /app/rq_worker/worker.py
    container_name: rq_worker
    depends_on:
      - app
      - redis
    volumes:
      - ./rq_worker:/app/rq_worker


volumes:
  pgdata:
